### ISSUE TITLE
Unable to update memorydb password

### ISSUE THREAD

**Issue by guitarrapc** [pulumi/pulumi-aws-native#399]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I was create MemoryDB with Pulumi.AwsNative dotnet SDK. Then trying to update Passwords for `Pulumi.AwsNative.MemoryDB.User.AuthenticationMode`. 
Pulumi preview indicate can update it as follows.

```
~  aws-native:memorydb:User (update)
    [id=foo]
    __inputs          : "[secret]"
    arn               : "arn:aws:memorydb:ap-northeast-1:123456790:user/foo"
    status            : "active"
```

However `pulumi up` failed with `error: transport is closing`.
Here's stack trace for the exception shown in pulumi up.

```
    panic: interface conversion: interface {} is *resource.Secret, not []interface {}
    goroutine 117 [running]:
    github.com/pulumi/pulumi-aws-native/provider/pkg/schema.(*sdkToCfnConverter).sdkTypedValueToCfn(0xc0009c1548, 0xc0009c0ee0, 0x2aced80, 0xc000990c10, 0xc0009c2088, 0xc0009c0e01)
        /home/runner/work/pulumi-aws-native/pulumi-aws-native/provider/pkg/schema/convert.go:63 +0x525
    github.com/pulumi/pulumi-aws-native/provider/pkg/schema.(*sdkToCfnConverter).sdkObjectValueToCfn(0xc0009c1548, 0xc000030588, 0x30, 0x2bd1320, 0xc000ffbdd0, 0xc000f922b9, 0xc000f922a0)
        /home/runner/work/pulumi-aws-native/pulumi-aws-native/provider/pkg/schema/convert.go:91 +0x1fa
    github.com/pulumi/pulumi-aws-native/provider/pkg/schema.(*sdkToCfnConverter).sdkTypedValueToCfn(0xc0009c1548, 0xc0009c1170, 0x2bd1320, 0xc000ffbdd0, 0x2bd1320, 0xc000ffbdd0)
        /home/runner/work/pulumi-aws-native/pulumi-aws-native/provider/pkg/schema/convert.go:58 +0x454
    github.com/pulumi/pulumi-aws-native/provider/pkg/schema.(*sdkToCfnConverter).valueToPatch(0xc0009c1548, 0x2e72461, 0x7, 0xc000f922a0, 0x12, 0x0, 0x0, 0xc000030580, 0x38, 0x0, ...)
        /home/runner/work/pulumi-aws-native/pulumi-aws-native/provider/pkg/schema/convert.go:132 +0x27c
    github.com/pulumi/pulumi-aws-native/provider/pkg/schema.(*sdkToCfnConverter).diffToPatch(0xc0009c1548, 0xc000982ae0, 0x0, 0xc00063ba40, 0xa0)
        /home/runner/work/pulumi-aws-native/pulumi-aws-native/provider/pkg/schema/convert.go:103 +0x76b
    github.com/pulumi/pulumi-aws-native/provider/pkg/schema.DiffToPatch(0xc0009c17c0, 0xc000763020, 0xc000982ae0, 0xc00063b9a0, 0x97, 0xc000982ae0, 0x0, 0x0)
        /home/runner/work/pulumi-aws-native/pulumi-aws-native/provider/pkg/schema/convert.go:28 +0x65
    github.com/pulumi/pulumi-aws-native/provider/pkg/provider.(*cfnProvider).Update(0xc000316280, 0x3227cc8, 0xc000ffaed0, 0xc000fac880, 0xc000316280, 0x2c15801, 0xc000ff3fc0)
        /home/runner/work/pulumi-aws-native/pulumi-aws-native/provider/pkg/provider/provider.go:871 +0x375
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1(0x3227cc8, 0xc000ffaed0, 0x2df02a0, 0xc000fac880, 0x2de2f20, 0x3e16368, 0x3227cc8, 0xc000ffaed0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/proto/go/provider.pb.go:2665 +0x90
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3227cc8, 0xc000ffa4b0, 0x2df02a0, 0xc000fac880, 0xc000982080, 0xc0008e54d0, 0x0, 0x0, 0x31c1a80, 0xc0001c6810)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x31c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler(0x2e34820, 0xc000316280, 0x3227cc8, 0xc000ffa4b0, 0xc000fa2e40, 0xc000771080, 0x3227cc8, 0xc000ffa4b0, 0xc000980000, 0x5d0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/proto/go/provider.pb.go:2667 +0x15e
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00065c8c0, 0x3235e18, 0xc000085080, 0xc000ffe000, 0xc000e5d020, 0x3dbe470, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc00065c8c0, 0x3235e18, 0xc000085080, 0xc000ffe000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000eb2080, 0xc00065c8c0, 0x3235e18, 0xc000085080, 0xc000ffe000)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xb2
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
```

### Steps to reproduce

1. Create MemoryDB and User.
2. Update User and run preview. -> success
3. Run `pulumi up` -> failed.

Expected: Update User password without error. 
Actual: Pulumi stopped without updating user password. 

### Workaround

Add `"authenticationMode"` to IgnoreChanges. Then update MemoryDB User Password directly on AWS Console or aws cli.

**Comment by viveklak** [comment]
Could you also provide some of your code to repro?

**Comment by guitarrapc** [comment]
@viveklak Here's sample code to reproduce.

```cs
var password = "0123456789abcdef"; // <- Update this.
var userOpt = new CustomResourceOptions { Parent = this, DeleteBeforeReplace = true, IgnoreChanges = new List<string>() { "tags", "authenticationMode" } };
var user = new User("foo", new UserArgs
{
    UserName = "foo",
    AccessString = "on ~* &* +@all", // sample. allow all.
    AuthenticationMode = new AuthenticationModePropertiesArgs
    {
        Type = UserAuthenticationModePropertiesType.Password,
        Passwords = password,
    },
}, userOpt);
```

Once created user, then update password cause error introduced.

**Comment by mikhailshilkov** [comment]
I believe a full repro has to have secrets in it. Here is the adjusted one that I tried:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws-native";

var password = "0123456789abcdef"; // <-- update this
var user = new aws.memorydb.User("foo", {
    userName: "foo",
    accessString: "on ~* &* +@all",
    authenticationMode: {
        type: aws.memorydb.UserAuthenticationModePropertiesType.Password,
        passwords: [password],
    },
});
```

I didn't hit the panic but I did hit an error updating:

```
  aws-native:memorydb:User (foo):
    error: operation error CloudControl: UpdateResource, https response error StatusCode: 400, RequestID: 12345713-a197-48e2-9b3d-b07f906aa4b5, api error ValidationException: Model validation failed (#/AuthenticationMode/Passwords/0: expected type: String, found: JSONObject)
```

I logged what we send to AWS and it's clearly wrong:

```
UpdateResource "AWS::MemoryDB::User" id "foo" token "1234586b-1aab-4c8a-9e73-800183bf37b5" state [{Operation:add Path:/AuthenticationMode Value:map[Passwords:[0x14001a26420] Type:password]}]
```

As I see, we send something wrong over the wire instead of the password value.

I think the solution is actually pretty simple, we should remove this line:

https://github.com/pulumi/pulumi-aws-native/blob/b7f77bdfbc864c0df5cab8e8b672d6a37905f3f3/provider/pkg/provider/provider.go#L465

This option is a bit tricky. If we set it to true, then in theory we can flow secretness through the computations. However, we don't really do that in AWS Native - we pass inputs to AWS CC API and get the outputs with no metadata connection. Azure Native has this option off, and we haven't seen any issues with it.

I suggest we adjust AcceptSecrets to false and review all secrets expectations in this provider.

**Comment by mjeffryes** [comment]
I'm no longer able to repro this issue. I think between #1009 and #1054, we're now doing a replace and sending the secrets correctly.
