### ISSUE TITLE
Python: IndentationError: expected an indented block after function definition on line 20

### ISSUE THREAD

**Issue by jcassee** [pulumi/pulumi-aws-native#465]
### What happened?

Got a Python syntax error trying to create a Route53 zone:
```
import pulumi_aws_native as aws_native
primary = aws_native.route53.Zone("primary")
```

### Steps to reproduce

1. Install Pulumi
2. Create Python project
3. Install pulumi-aws-native 0.15.0
4. Try to create a Route53 zone:
    ```
    import pulumi_aws_native as aws_native
    primary = aws_native.route53.Zone("primary")
    ```
5. `pulumi up`

### Expected Behavior

Zone is created

### Actual Behavior

    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
        return future.result()
      File "/home/joost/Ontwikkeling/Freightdog/infra-pulumi/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/joost/Ontwikkeling/Freightdog/infra-pulumi/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/home/joost/Ontwikkeling/Freightdog/infra-pulumi/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/home/joost/Ontwikkeling/Freightdog/infra-pulumi/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/usr/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/lib/python3.10/runpy.py", line 286, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/home/joost/Ontwikkeling/Freightdog/infra-pulumi/./__main__.py", line 5, in <module>
        primary = aws_native.route53.Zone("primary")
      File "/usr/lib/python3.10/importlib/util.py", line 247, in __getattribute__
        self.__spec__.loader.exec_module(self)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/joost/Ontwikkeling/Freightdog/infra-pulumi/.venv/lib/python3.10/site-packages/pulumi_aws_native/route53/__init__.py", line 10, in <module>
        from .get_dnssec import *
      File "/home/joost/Ontwikkeling/Freightdog/infra-pulumi/.venv/lib/python3.10/site-packages/pulumi_aws_native/route53/get_dnssec.py", line 23
        class AwaitableGetDNSSECResult(GetDNSSECResult):
    IndentationError: expected an indented block after function definition on line 20
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

### Versions used

CLI          
Version      3.28.0
Go Version   go1.18
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.2.0
aws-native  0.15.0
python      unknown

Host     
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in python (/home/joost/Ontwikkeling/Freightdog/infra-pulumi/.venv/bin/python3 v3.10.4)

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/XXX
User           XXX
Organizations  XXX

NAME               VERSION
pip                21.3.1
pulumi-aws         5.2.0
pulumi-aws-native  0.15.0
setuptools         60.1.0
wheel              0.37.1

Pulumi locates its logs in /tmp by default

### Additional context

Cause is a missing `pass` in [get_dnssec.py](https://github.com/pulumi/pulumi-aws-native/blob/543d08b33e857e90f48d013503d2f80d855eb493/sdk/python/pulumi_aws_native/route53/get_dnssec.py#L21).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by inhumantsar** [comment]
this is also happening with `ecr` and has been since 0.6.0. codegen is producing bad syntax for python.

```
    error: Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/Users/sam/.pyenv/versions/3.9.11/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
        return future.result()
      File "/Users/sam/.pyenv/versions/aws-sso-pulumi/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/sam/.pyenv/versions/aws-sso-pulumi/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/Users/sam/.pyenv/versions/aws-sso-pulumi/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/sam/.pyenv/versions/aws-sso-pulumi/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/Users/sam/.pyenv/versions/3.9.11/lib/python3.9/runpy.py", line 285, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/Users/sam/.pyenv/versions/3.9.11/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/Users/sam/Source/aws-sso/./__main__.py", line 8, in <module>
        from maersk.iam import PolicyStatement, create_policy
      File "/Users/sam/.pyenv/versions/aws-sso-pulumi/lib/python3.9/site-packages/maersk/__init__.py", line 270, in <module>
        from ._launch import launch
      File "/Users/sam/.pyenv/versions/aws-sso-pulumi/lib/python3.9/site-packages/maersk/_launch.py", line 9, in <module>
        from maersk.deployment import create_pipeline
      File "/Users/sam/.pyenv/versions/aws-sso-pulumi/lib/python3.9/site-packages/maersk/deployment.py", line 38, in <module>
        from maersk.ecs.ecs import get_ecs_artifact_path, get_task_definition_arn
      File "/Users/sam/.pyenv/versions/aws-sso-pulumi/lib/python3.9/site-packages/maersk/ecs/ecs.py", line 30, in <module>
        from pulumi_aws_native.ecr.repository import (
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 978, in _find_and_load_unlocked
      File "/Users/sam/.pyenv/versions/3.9.11/lib/python3.9/importlib/util.py", line 245, in __getattribute__
        self.__spec__.loader.exec_module(self)
      File "/Users/sam/.pyenv/versions/aws-sso-pulumi/lib/python3.9/site-packages/pulumi_aws_native/ecr/__init__.py", line 10, in <module>
        from .get_pull_through_cache_rule import *
      File "/Users/sam/.pyenv/versions/aws-sso-pulumi/lib/python3.9/site-packages/pulumi_aws_native/ecr/get_pull_through_cache_rule.py", line 23
        class AwaitableGetPullThroughCacheRuleResult(GetPullThroughCacheRuleResult):
    IndentationError: expected an indented block
```

https://github.com/pulumi/pulumi-aws-native/blob/master/sdk/python/pulumi_aws_native/ecr/get_pull_through_cache_rule.py

**Comment by mjeffryes** [comment]
I believe this was fixed with https://github.com/pulumi/pulumi/issues/9358. Please feel free to reopen if this issue reappears
