### ISSUE TITLE
Unable to create Sagemaker domain due to missing paren in generated code

### ISSUE THREAD

**Issue by jspiewak** [pulumi/pulumi-aws-native#497]
### What happened?

I am trying to create a Sagemaker domain, but get an exception when running `pulumi preview`.

### Steps to reproduce

Create a Sagemaker domain, e..g:

```
        assume_role_policy = aws.iam.get_policy_document(statements=[aws.iam.GetPolicyDocumentStatementArgs(
            actions=['sts:AssumeRole'],
            principals=[aws.iam.GetPolicyDocumentStatementPrincipalArgs(
                type='Service',
                identifiers=['sagemaker.amazonaws.com'],
            )]
        )])
        domain_setting_policy = aws.iam.get_policy_document(statements=[aws.iam.GetPolicyDocumentStatementArgs(
            actions=[
                'license-manager:ExtendLicenseConsumption',
                'license-manager:ListReceivedLicenses',
                'license-manager:GetLicense',
                'license-manager:CheckoutLicense',
                'license-manager:CheckInLicense',
                'logs:CreateLogDelivery',
                'logs:CreateLogGroup',
                'logs:CreateLogStream',
                'logs:DeleteLogDelivery',
                'logs:Describe*',
                'logs:GetLogDelivery',
                'logs:GetLogEvents',
                'logs:ListLogDeliveries',
                'logs:PutLogEvents',
                'logs:PutResourcePolicy',
                'logs:UpdateLogDelivery'
            ]
        )])
        domain_execution_role = aws.iam.Role(
            'sagemaker-domain-execution-role',
            aws.iam.RoleArgs(
                name='SagemakerDomainExecution',
                path='/',
                assume_role_policy=assume_role_policy.json,
                inline_policies=[aws.iam.RoleInlinePolicyArgs(
                    name='domain-setting-policy',
                    policy=domain_setting_policy.json
                )]
            ))

        default_execution_role = aws.iam.Role(
            'sagemaker-execution-role',
            aws.iam.RoleArgs(
                name='SagemakerExecution',
                path='/',
                assume_role_policy=assume_role_policy.json,
                managed_policy_arns=['arn:aws:iam::aws:policy/AmazonSageMakerFullAccess']
                # NB: might need inline policy as well for S3 access, etc.
            ))

        self.domain = awsn.sagemaker.Domain(
            f'sagemaker-demo-{pulumi.get_stack()}',
            awsn.sagemaker.DomainArgs(
                domain_name=f'demo-{pulumi.get_stack()}',
                auth_mode=awsn.sagemaker.DomainAuthMode.SSO,
                vpc_id=self.vpc.vpc.id,
                subnet_ids=[subnet.id for subnet in self.vpc.subnets[Privacy.PRIVATE]],
                domain_settings=awsn.sagemaker.DomainSettingsArgs(
                    r_studio_server_pro_domain_settings=awsn.sagemaker.DomainRStudioServerProDomainSettingsArgs(
                        domain_execution_role_arn=domain_execution_role.arn
                    )
                ),
                default_user_settings=awsn.sagemaker.DomainUserSettingsArgs(
                    execution_role=default_execution_role.arn
                ),
                app_network_access_type=awsn.sagemaker.DomainAppNetworkAccessType.PUBLIC_INTERNET_ONLY,
                tags=[awsn.sagemaker.DomainTagArgs(key=k, value=v) for k, v in tags.items()]
            ),
            opts=pulumi.ResourceOptions(parent=self)
        )
```

### Expected Behavior

The domain is previewed.

### Actual Behavior

Exception:

```
error: Program failed with an unhandled exception:
error: Traceback (most recent call last):
  File "/Users/jss/.pulumi/bin/pulumi-language-python-exec", line 107, in <module>
    loop.run_until_complete(coro)
  File "/Users/jss/.pyenv/versions/3.9.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jss/.pyenv/versions/3.9.9/envs/aws-sol-eng/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
    await run_pulumi_func(lambda: Stack(func))
  File "/Users/jss/.pyenv/versions/3.9.9/envs/aws-sol-eng/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
    func()
  File "/Users/jss/.pyenv/versions/3.9.9/envs/aws-sol-eng/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
    await run_pulumi_func(lambda: Stack(func))
  File "/Users/jss/.pyenv/versions/3.9.9/envs/aws-sol-eng/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 149, in __init__
    func()
  File "/Users/jss/.pulumi/bin/pulumi-language-python-exec", line 106, in <lambda>
    coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
  File "/Users/jss/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 285, in run_path
    return _run_code(code, mod_globals, init_globals,
  File "/Users/jss/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jss/work/rstudio/aws-sol-eng/./__main__.py", line 46, in <module>
    sagemaker.Sagemaker()
  File "/Users/jss/work/rstudio/aws-sol-eng/./sagemaker.py", line 23, in __init__
    self._domain(tags)
  File "/Users/jss/work/rstudio/aws-sol-eng/./sagemaker.py", line 89, in _domain
    self.domain = awsn.sagemaker.Domain(
  File "/Users/jss/.pyenv/versions/3.9.9/lib/python3.9/importlib/util.py", line 245, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/jss/.pyenv/versions/3.9.9/envs/aws-sol-eng/lib/python3.9/site-packages/pulumi_aws_native/sagemaker/__init__.py", line 28, in <module>
    from .get_feature_group import *
  File "/Users/jss/.pyenv/versions/3.9.9/envs/aws-sol-eng/lib/python3.9/site-packages/pulumi_aws_native/sagemaker/get_feature_group.py", line 23
    class AwaitableGetFeatureGroupResult(GetFeatureGroupResult):
IndentationError: expected an indented block
```

### Versions used

$ pulumi about
CLI          
Version      3.32.1
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.4.0
aws-native  0.16.1
eks         0.40.0
kubernetes  3.15.0
python      unknown

Host     
OS       darwin
Version  12.3.1
Arch     arm64

### Additional context

There is a missing closing paren:

https://github.com/pulumi/pulumi-aws-native/blob/master/sdk/python/pulumi_aws_native/sagemaker/get_feature_group.py#L48

And the `__init__` method is empty without a `pass` statement.

If I edit the file locally, the preview works.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jspiewak** [comment]
Strikingly similar to #482

**Comment by jspiewak** [comment]
Searching the code, there appear to be 19 cases of this generation bug:

1. pulumi_aws_native.acmpca.get_permission.py
2. pulumi_aws_native.appstream.get_application_entitlement_association.py
3. pulumi_aws_native.appstream.get_application_fleet_association.py
4. pulumi_aws_native.autoscaling.get_launch_configuration.py
5. pulumi_aws_native.cloudformation.get_module_default_version.py
6. pulumi_aws_native.ecr.get_pull_through_cache_rule.py
7. pulumi_aws_native.glue.get_schema_version_metadata.py
8. pulumi_aws_native.guardduty.get_master.py
9. pulumi_aws_native.location.get_tracker_consumer.py
10. pulumi_aws_native.networkmanager.get_customer_gateway_association.py
11. pulumi_aws_native.networkmanager.get_link_association.py
12. pulumi_aws_native.networkmanager.get_transit_gateway_registration.py
13. pulumi_aws_native.route53.get_dnssec.py
14. pulumi_aws_native.sagemaker.get_feature_group.py
15. pulumi_aws_native.servicecatalog.get_service_action_association.py
16. pulumi_aws_native.ses.get_configuration_set.py
17. pulumi_aws_native.signer.get_profile_permission.py
18. pulumi_aws_native.sso.get_assignment.py
19. pulumi_aws_native.wafv2.get_web_aclassociation.py

**Comment by viveklak** [comment]
This seems to be another instance of https://github.com/pulumi/pulumi/issues/9358

**Comment by viveklak** [comment]
On further investigation, the root cause seems to be that we are excluding create-only properties from outputs for invokes: https://github.com/pulumi/pulumi-aws-native/blame/master/provider/pkg/schema/gen.go#L604-L606. But in some cases, all properties are create-only, e.g.: https://github.com/pulumi/pulumi-aws-native/blob/master/aws-cloudformation-schema/aws-sagemaker-featuregroup.json
