### ISSUE TITLE
import of ELB ListenerRule does not correctly fill out Listener ARN

### ISSUE THREAD

**Issue by xiongchiamiov** [pulumi/pulumi-aws-native#660]
### What happened?

I'm importing the first bits of our existing infrastructure into Pulumi.  Specifically, I'm trying to import the various definitions for an ALB so that I can add a new forwarding rule.

After importing the two Listeners, importing a ListenerRule that's attached to one of them produces code that does not associate the rule to the Listener.

Additionally, adding that association in code does not lead to a no-op state update, but that might be a mistake on my part.

### Steps to reproduce

Suspected minimal reproduction steps:

1. Create a listener for an application load balancer, including at least one rule, outside of Pulumi.
2. Import the listener.
3. Import a listener rule.

### Expected Behavior

1. When doing `pulumi import`, I expected the generated code to be exactly matching the existing component in AWS and to not generate any warnings.
2. When adding the arn for the listener that I know the rule is attached to, I expected there to be no diff displayed in `pulumi up`.
3. When executing the change, I expected it to not produce an error.
4. Importing a component should not put my stack in a state where I can no longer run my pulumi program without deleting my imported (and in use) resource.

### Actual Behavior

1. I imported two Listeners: `[$]> pulumi import aws-native:elasticloadbalancingv2:Listener winnielabs-web-80 arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:listener/app/winnielabs-web/aeba2740bb970eea/
f591a0c11ef000fd` and `[$]> pulumi import aws-native:elasticloadbalancingv2:Listener winnielabs-web-443 arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:listener/app/winnielabs-web/aeba2740bb970eea
/ce17cdcd5978a7ad`
including adding the generated code to my Pulumi program and running `pulumi up`.  There were no changes on the `up` operation.
2. I ran an import of one of the rules attached to the first listener:

```
[$]> pulumi import aws-native:elasticloadbalancingv2:ListenerRule winnielabs-web-80-wp-
login arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:listener-rule/app/winnielabs-web/aeba2740bb970eea/f591a0c11ef000fd/37de0401f49d9150
Previewing import (staging)

View Live: https://app.pulumi.com/xiongchiamiov/aws/staging/previews/5230b925-037b-4636-abe5-658035d5c852

     Type                                               Name                        Plan
     pulumi:pulumi:Stack                                aws-staging
 =   └─ aws-native:elasticloadbalancingv2:ListenerRule  winnielabs-web-80-wp-login

Diagnostics:
  aws-native:elasticloadbalancingv2:ListenerRule (winnielabs-web-80-wp-login):
    warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `aws-native` provider. The import will still proceed, but you will need to edit
the generated code after copying it into your program.
    warning: aws-native:elasticloadbalancingv2:ListenerRule resource 'winnielabs-web-80-wp-login': property listenerArn value {<nil>} has a problem: missing required property list
enerArn


Do you want to perform this import?  [Use arrows to move, enter to select, type to filter
Do you want to perform this import?  [Use arrows to move, enter to select, type to filter
Do you want to perform this import? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:staging::aws::pulumi:pulumi:Stack::aws-staging]
    = aws-native:elasticloadbalancingv2:ListenerRule: (import) 🔒
        [id=arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:listener-rule/app/winnielabs-web/aeba2740bb970eea/f591a0c11ef000fd/37de0401f49d9150]
        [urn=urn:pulumi:staging::aws::aws-native:elasticloadbalancingv2:ListenerRule::winnielabs-web-80-wp-login]
        [provider=urn:pulumi:staging::aws::pulumi:providers:aws-native::default_0_29_0::84684737-b142-4290-a707-3f0b1ae64f60]
        actions   : [
            [0]: {
                forwardConfig : {
                    targetGroupStickinessConfig: {
                        enabled: false
                    }
                    targetGroups               : [
                        [0]: {
                            targetGroupArn: "arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:targetgroup/winnielabs-limbo/24da67e371c5146e"
                            weight        : 1
                        }
                    ]
                }
                targetGroupArn: "arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:targetgroup/winnielabs-limbo/24da67e371c5146e"
                type          : "forward"
            }
        ]
        conditions: [
            [0]: {
                field            : "path-pattern"
                pathPatternConfig: {
                    values: [
                        [0]: "/wp-login.php"
                    ]
                }
                values           : [
                    [0]: "/wp-login.php"
                ]
            }
        ]
        priority  : 1

Do you want to perform this import?  [Use arrows to move, enter to select, type to filter
Do you want to perform this import?  [Use arrows to move, enter to select, type to filter
Do you want to perform this import? yes
Importing (staging)

View Live: https://app.pulumi.com/xiongchiamiov/aws/staging/updates/76

     Type                                               Name                        Stat
     pulumi:pulumi:Stack                                aws-staging
 =   └─ aws-native:elasticloadbalancingv2:ListenerRule  winnielabs-web-80-wp-login
Diagnostics:
  aws-native:elasticloadbalancingv2:ListenerRule (winnielabs-web-80-wp-login):
    warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `aws-native` provider. The import will still proceed, but you will need to edit
the generated code after copying it into your program.
    warning: aws-native:elasticloadbalancingv2:ListenerRule resource 'winnielabs-web-80-wp-login': property listenerArn value {<nil>} has a problem: missing required property list
enerArn

Resources:
    = 1 imported
    6 unchanged

Duration: 2s

Please copy the following code into your Pulumi application. Not doing so
will cause Pulumi to report that an update will happen on the next update command.

Please note that the imported resources are marked as protected. To destroy them
you will need to remove the `protect` option and run `pulumi update` *before*
the destroy will take effect.

import pulumi
import pulumi_aws_native as aws_native

winnielabs_web_80_wp_login = aws_native.elasticloadbalancingv2.ListenerRule("winnielabs-web-80-wp-login",
    actions=[aws_native.elasticloadbalancingv2.ListenerRuleActionArgs(
        forward_config=aws_native.elasticloadbalancingv2.ListenerRuleForwardConfigArgs(
            target_group_stickiness_config=aws_native.elasticloadbalancingv2.ListenerRuleTargetGroupStickinessConfigArgs(
                enabled=False,
            ),
            target_groups=[aws_native.elasticloadbalancingv2.ListenerRuleTargetGroupTupleArgs(
                target_group_arn="arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:targetgroup/winnielabs-limbo/24da67e371c5146e",
                weight=1,
            )],
        ),
        target_group_arn="arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:targetgroup/winnielabs-limbo/24da67e371c5146e",
        type="forward",
    )],
    conditions=[aws_native.elasticloadbalancingv2.ListenerRuleRuleConditionArgs(
        field="path-pattern",
        path_pattern_config=aws_native.elasticloadbalancingv2.ListenerRulePathPatternConfigArgs(
            values=["/wp-login.php"],
        ),
        values=["/wp-login.php"],
    )],
    listener_arn="",
    priority=1,
    opts=pulumi.ResourceOptions(protect=True))
```
Note here that `listener_arn` is set to an empty string.
3. I added the generated code, but then changed `listener_arn=""` to `listener_arn=winnielabs_web_80` to reference the already-imported listener.
4. I ran `pulumi up` and saw that it wanted to add the field.  This seemed like an error in the state to me (the rule was created as part of the listener and is indeed attached) and so I told it to continue.  This returned an error because that is an immutable field:

```
[$]> pulumi up
Previewing update (staging)

View Live: https://app.pulumi.com/xiongchiamiov/aws/staging/previews/7453743a-21ea-4906-b144-cdabbcdbafa9

     Type                                               Name                        Plan
     pulumi:pulumi:Stack                                aws-staging
 ~   └─ aws-native:elasticloadbalancingv2:ListenerRule  winnielabs-web-80-wp-login

Resources:
    ~ 1 to update
    6 unchanged

Do you want to perform this update?  [Use arrows to move, enter to select, type to filter
Do you want to perform this update?  [Use arrows to move, enter to select, type to filter
Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:staging::aws::pulumi:pulumi:Stack::aws-staging]
    ~ aws-native:elasticloadbalancingv2:ListenerRule: (update) 🔒
        [id=arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:listener-rule/app/winnielabs-web/aeba2740bb970eea/f591a0c11ef000fd/37de0401f49d9150]
        [urn=urn:pulumi:staging::aws::aws-native:elasticloadbalancingv2:ListenerRule::winnielabs-web-80-wp-login]
        [provider=urn:pulumi:staging::aws::pulumi:providers:aws-native::default_0_29_0::84684737-b142-4290-a707-3f0b1ae64f60]
      + listenerArn: "arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxxx:listener/app/winnielabs-web/aeba2740bb970eea/f591a0c11ef000fd"

Do you want to perform this update?  [Use arrows to move, enter to select, type to filter
Do you want to perform this update?  [Use arrows to move, enter to select, type to filter
Do you want to perform this update? yes
Updating (staging)

View Live: https://app.pulumi.com/xiongchiamiov/aws/staging/updates/77

     Type                                               Name                        Stat
     pulumi:pulumi:Stack                                aws-staging                 **fa
 ~   └─ aws-native:elasticloadbalancingv2:ListenerRule  winnielabs-web-80-wp-login

Diagnostics:
  aws-native:elasticloadbalancingv2:ListenerRule (winnielabs-web-80-wp-login):
    error: operation error CloudControl: UpdateResource, https response error StatusCode: 400, RequestID: 3f591d54-d34b-4e55-9df1-1a27ae1a8298, NotUpdatableException: Invalid patch update: createOnlyProperties [/properties/ListenerArn] cannot be updated

  pulumi:pulumi:Stack (aws-staging):
    error: update failed
```
5. Since the diff said it was _adding_ the arn field, I also tried commenting that line out, but that produces an error as well:
```
Diagnostics:
  pulumi:pulumi:Stack (aws-staging):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/jamesph/Documents/winfrastructure/aws/./__main__.py", line 150, in <module>
        winnielabs_web_80_wp_login = elasticloadbalancingv2.ListenerRule("winnielabs-web-80-wp-login",
      File "/Users/jamesph/Documents/winfrastructure/aws/venv/lib/python3.10/site-packages/pulumi_aws_native/elasticloadbalancingv2/listener_rule.py", line 103, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
      File "/Users/jamesph/Documents/winfrastructure/aws/venv/lib/python3.10/site-packages/pulumi_aws_native/elasticloadbalancingv2/listener_rule.py", line 128, in _internal_init
        raise TypeError("Missing required property 'listener_arn'")
    TypeError: Missing required property 'listener_arn'
```

### Output of `pulumi about`

```
[$]> pulumi about
CLI
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws-native  0.29.0
python      unknown

Host
OS       darwin
Version  12.6
Arch     arm64

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.10.8
'

Current Stack: staging

TYPE                                            URN
pulumi:pulumi:Stack                             urn:pulumi:staging::aws::pulumi:pulumi:Stack::aws-staging
pulumi:providers:aws-native                     urn:pulumi:staging::aws::pulumi:providers:aws-native::default_0_29_0
aws-native:ecs:Cluster                          urn:pulumi:staging::aws::aws-native:ecs:Cluster::winnie
aws-native:ecs:TaskDefinition                   urn:pulumi:staging::aws::aws-native:ecs:TaskDefinition::winnie-web-task-staging
aws-native:elasticloadbalancingv2:Listener      urn:pulumi:staging::aws::aws-native:elasticloadbalancingv2:Listener::winnielabs-web-443
aws-native:elasticloadbalancingv2:Listener      urn:pulumi:staging::aws::aws-native:elasticloadbalancingv2:Listener::winnielabs-web-80
aws-native:ecs:Service                          urn:pulumi:staging::aws::aws-native:ecs:Service::winnie-web-staging
aws-native:elasticloadbalancingv2:ListenerRule  urn:pulumi:staging::aws::aws-native:elasticloadbalancingv2:ListenerRule::winnielabs-web-80-wp-login


Found no pending operations associated with staging

Backend
Name           pulumi.com
URL            https://app.pulumi.com/xiongchiamiov
User           xiongchiamiov
Organizations  xiongchiamiov

Dependencies:
NAME               VERSION
pip                22.2.2
pulumi-aws-native  0.29.0
setuptools         65.3.0
wheel              0.37.1

Pulumi locates its logs in /var/folders/v9/9fdfk9j109ndft37cst980c00000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by xiongchiamiov** [comment]
As a note, when `pulumi import` told me that the verification step had failed, I interpreted that as "you'll need to adjust the generated code in order to get it correctly generating a zero-diff configuration", not as "neither the generated code _nor_ the imported state will have the correct mapping of what's in aws, so you'll have to execute change operations on the aws api" (which I think is what happened).  Those are subtly different and the second is rather more dangerous, and if I'd understood that I would've aborted the import.  So there might be some clarity work to do on the warning message there.

**Comment by xiongchiamiov** [comment]
For reference, have dealt with this for now by doing a `stack delete` and then a re-import using aws-classic.

**Comment by guineveresaenger** [comment]
Hi @xiongchiamiov - thank you for reporting this issue, and for the detailed writeup. 

We also appreciate knowing that this import works correctly in AWS Classic and will take a look as soon as we can.
